#!/bin/bash

## creating temp directory
mkdir ~/temp
mv MullvadVPN*.deb ~/temp
cd ~/temp
## unpacking .deb file and the data tarball inside
ar -x MullvadVPN*.deb
tar -xf data.tar.xz
## moving essential files
mv opt/'Mullvad VPN' /opt
mv usr/bin/mullvad-daemon /usr/bin
mv usr/lib/systemd/system/mullvad-daemon.service /usr/lib/systemd/system
chmod +x /usr/lib/systemd/system/mullvad-daemon.service
## making .desktop file
mv usr/share/icons/hicolor/1024x1024/apps/mullvad-vpn.png /opt/'Mullvad VPN'
touch .local/share/applications/mullvadvpn.desktop
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=/opt/'Mullvad VPN'/mullvad-vpn
Name=MullvadVPN
Icon=/opt/'Mullvad VPN'/mullvad-vpn.png
" >> .local/share/applications/mullvadvpn.desktop
## starting service
systemctl enable --now mullvad-daemon
## deleting temp directory
rm -r ~/temp
